version: '3.8'

services:
  workshop-customers-api:
    image: costinelnegura/workshop-customers-api:latest
    build:
      context: .
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3318
      MYSQL_DATABASE: workshop_customers_db
      MYSQL_USER: root
      MYSQL_PASSWORD: hfr6Y-34ApW-sP14J
      AUTH_VALIDATE_TOKEN_API_URL: /api/v1/auth/validate
      SPRING_APPLICATION_NAME: workshop-customers-api
      EUREKA_SERVER_URI: http://host.docker.internal:8761/eureka
#      ZIPKIN_SERVER_URI: http://host.docker.internal:9411
#      RABBITMQ_SERVER_URI: amqp://guest:guest@host.docker.internal:5672
#      RABBITMQ_SERVER_HOST: host.docker.internal
#      RABBITMQ_SERVER_PORT: 5672
#      RABBITMQ_SERVER_USER: guest
#      RABBITMQ_SERVER_PASSWORD: guest
#      ZIPKIN_SENDER_TYPE: rabbit
      PORT: 8081
    ports:
        - "8081:8081"
    networks:
      - workshop_network
networks:
  workshop_network:
    external: true