server:
  port: ${PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:customers_db}
    username: ${MYSQL_USER:costinelnegura}
    password: ${MYSQL_PASSWORD:wytkyn-Kavmof-sipvo5}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        c3p0:
          min_size: 5
          max_size: 20
          timeout: 300
          max_statements: 50
          idle_test_period: 3000
          acquire_increment: 5
          validate: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: org.hibernate.dialect.MySQLDialect
  application:
    name: ${SPRING_APPLICATION_NAME:workshop-customers-api}
auth:
  validateTokenApiUrl: ${AUTH_VALIDATE_TOKEN_API_URL:/api/v1/auth/validate}
#logging:
#  level:
#    com.rabbitmq: DEBUG